[package]
name = "file-rotate"
version = "0.7.1"
authors = ["Kevin Robert Stravers <macocio@gmail.com>", "Erlend Langseth <3rlendhl@gmail.com>"]
edition = "2018"
description = "Log rotation for files"
homepage = "https://github.com/BourgondAries/file-rotate"
repository = "https://github.com/BourgondAries/file-rotate"
keywords= ["log", "rotate", "logrotate"]
license = "MIT"

[dependencies]
chrono = {version = "0.4.20", optional = true }
flate2 = "1.0"
crossbeam = { version = "0.8.1", optional = true }
rustix = { version = "0.36.6", features = ["process"] }
fork = "0.1.20"

[dev-dependencies]
filetime = "0.2"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
tempdir = "0.3.7"

[features]
default = ["chrono04"]
chrono04 = ["chrono"]
notify = ["crossbeam"]